version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /cloud-cicd/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /cloud-cicd/docker-credentials/password
    DOCKER_REGISTRY_URL: /cloud-cicd/docker-registry/url
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "Pre-build phase..."
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-yatra-svc:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-yatra-svc:latest"
  post_build:
    commands:
      - echo "Build on `date` completed successfully!"
artifacts:
  files:
    - target/simple-yatra-svc-0.0.1-SNAPSHOT.jar