spring:
  application:
    name: simple-yatra-svc
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: sa
      password: sa
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs

server:
  port: 9091