spring:
  application:
    name: simple-yatra-svc
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: sa
      password: sa
  datasource:
#    Postgres local connection ----->
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs

server:
  port: 9091